# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 416462cad154a38215006c74afb1a873e1bdfdde4d8a74090067e1454dcc2a574bb7b159531ca3063f2e44f3c98e4efa0f79cb83f9e6ca9e2de48b0b38870cc1

test:
  secret_key_base: 5f5d766af621d95687343827743cff29f1498b3cef6001f0e5633fc0ad59a72fd4dd118397153ccfe24ae192cec62e00571344cf650f388d8109d2828de7334b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
